### ISSUE TITLE
Items as part of first assignment

### ISSUE THREAD

**Issue by dhruvilk** [dhruvilk/CS673#12]
Your team has identified articulated a far vision for the product. It is clearly documented in your git repo's README.

Your team has identified articulated a near vision for the first iteration of the product, which you will build in this project. It is clearly documented in your git repo's README.

Your team has identified at least three stakeholder types whose needs are fulfilled by your product. They are clearly documented in your git repo's README.

Your team has constructed a detailed user persona for your real stakeholder. The user persona details are clearly documented in your git repo's README.

**Comment by WheatOnToast** [comment]
**### Completed these questions within commit 78059aa:**

Your team has identified articulated a far vision for the product. It is clearly documented in your git repo's README.

Your team has identified articulated a near vision for the first iteration of the product, which you will build in this project. It is clearly documented in your git repo's README.

Your team has identified at least three stakeholder types whose needs are fulfilled by your product. They are clearly documented in your git repo's README.

Your team has constructed a detailed user persona for your real stakeholder. The user persona details are clearly documented in your git repo's README.
